name: 'Delete Releases'
description: 'delete a release according to its id or name'
inputs:
  repo:
    description: 'Operation target repository, the format is "owner/repo".'
    required: true
    default: ''

  release-drop:
    description: 'Whether to delete the release.'
    required: true
    default: 'false'
  release-keep-count:
    description: 'The number of releases except the latest release reserved, "-1" means delete all.'
    required: true
    default: '0'
  release-drop-tag:
    description: 'Whether to delete the tag of release.'
    required: true
    default: 'true'

  pre-release-drop:
    description: 'Whether to delete the pre-release.'
    required: true
    default: 'false'
  pre-release-keep-count:
    description: 'The number of pre-release except the latest pre-release reserved, "-1" means delete all.'
    required: true
    default: '0'
  pre-release-drop-tag:
    description: 'Whether to delete the tag of pre-release.'
    required: true
    default: 'true'

  draft-drop:
    description: 'Whether to delete the draft.'
    required: true
    default: 'true'
runs:
  using: 'node16'
  main: 'dist/index.js'